### ISSUE TITLE
Podcast list no longer showing

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-flutter-community/musicpod#789]
I used to get a list of podcast episodes in previous versions (before podcast refreshing got added), now I see a big grey box:

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1146853/ea324011-e9e4-40be-947d-e7457fb3f399)

If I click play and accept the warning about adding N podcast, I can eventually reproduce them

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/1146853/d3ab83ba-a8b1-445f-986d-c71858cd3323)

**Comment by Feichtmeier** [comment]
> I used to get a list of podcast episodes in previous versions (before podcast refreshing got added), now I see a big grey box:
> 
> ![image](https://private-user-images.githubusercontent.com/1146853/339132925-ea324011-e9e4-40be-947d-e7457fb3f399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMjc1NTMsIm5iZiI6MTcxODIyNzI1MywicGF0aCI6Ii8xMTQ2ODUzLzMzOTEzMjkyNS1lYTMyNDAxMS1lOWU0LTQwYmUtOTQ3ZC1lNzQ1N2ZiM2YzOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMjEyMDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA1MWI5M2NmZGYzMGE4NzRjOWNjYWE2OTI5YWNhYjNlNDI0ZDkxM2M0NjdlYjNlZTkxMTNiZWNlYmY4NGYzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qSNJ9tOR2B49fRXmcVLKVJWErz3wJaOYQaUsHyF8M6E)
> 
> If I click play and accept the warning about adding N podcast, I can eventually reproduce them
> 
> ![image](https://private-user-images.githubusercontent.com/1146853/339133267-d3ab83ba-a8b1-445f-986d-c71858cd3323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMjc1NTMsIm5iZiI6MTcxODIyNzI1MywicGF0aCI6Ii8xMTQ2ODUzLzMzOTEzMzI2Ny1kM2FiODNiYS1hOGIxLTQ0NWYtOTg2ZC1jNzE4NThjZDMzMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMjEyMDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRkYTUyNzExYTcyMTU1ODA5ZTEzOTcwM2EyN2FkNDc1ZjZlYzc2ODM4NWY4MzI0NjJlN2Y3ZDYyMTc0ZmQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LBsjAJH5XZiroY63ouU8teCqLsY-orJ_fSESjZQNLA8)

hm, can not reproduce here
could you start it from the terminal and see if there is any output?
and generally, does this issue persist after restart of the app?

**Comment by sergiusens** [comment]
It is, seems locale related:

```
* (musicpod:1075650): WARNING **: 08:52:32.131: Failed to set up Flutter locales
media_kit: VideoOutput: video_output_new: 2670229327440
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 2670229327440, id: 2670032070544, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 2670032070544
flutter: Invalid argument(s): Invalid locale "und"
flutter: #0      _throwLocaleError (package:intl/src/intl_helpers.dart:208)
flutter: #1      verifiedLocale (package:intl/src/intl_helpers.dart:202)
flutter: #2      new DateFormat (package:intl/src/intl/date_format.dart:267)
flutter: #3      new DateFormat.yMMMEd (package:intl/src/intl/date_format.dart:549)
flutter: #4      PodcastAudioTile.build (package:musicpod/src/podcasts/view/podcast_audio_tile.dart:61)
flutter: #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #52     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:858)
flutter: #53     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
flutter: #54     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844)
flutter: #55     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
flutter: #56     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
flutter: #57     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2686)
flutter: #58     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097)
flutter: #59     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2686)
flutter: #60     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
flutter: #61     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:424)
flutter: #62     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:77)
flutter: #63     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #64     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
flutter: #65     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1555)
flutter: #66     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1464)
flutter: #67     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #68     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #71     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #73     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #74     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #76     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #77     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #79     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #80     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #82     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #83     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #85     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #86     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #88     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #89     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #91     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569)
flutter: #92     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #93     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #95     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #96     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #98     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #99     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
```

I am on Ubuntu 22.04, these are my settings:

```
sergiusens@cuivienen:~$ env | grep LC_
LC_ADDRESS=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_MONETARY=pt_BR.UTF-8
LC_PAPER=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_CTYPE=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_NUMERIC=pt_BR.UTF-8
sergiusens@cuivienen:~$ env | grep LANG
LANGUAGE=en_US:
LANG=en_US.UTF-8
```

**Comment by Feichtmeier** [comment]
> podcast_audio_tile

ha :D Okay I think the year property might be empty or at least formatting doesn't work the way it normally does for a certain episode in there :)

https://github.com/ubuntu-flutter-community/musicpod/blob/b19908ad5964b7c299c919b2adf5c20344d8bf4e/lib/src/podcasts/view/podcast_audio_tile.dart#L61C11-L61C113

Thanks, will add a fix later (hopefully) or at night

**Comment by Feichtmeier** [comment]
@sergiusens fix should be in edge in 20 minutes

**Comment by sergiusens** [comment]
works great now.
Likewise for musicpod!
